-- ORD-audit PREVIEW
-- Kör DENNA FÖRST i Supabase SQL Editor.
-- Den visar alla rader som fix-ord.sql skulle uppdatera.
-- Granska — om allt ser rätt ut, kör fix-ord.sql.

WITH planned_fixes (word, from_letter, to_letter, confidence, why) AS (
  VALUES
    ('OFFERT', 'B', 'D', 'high', 'kostnadsförslag'),
    ('PROPORTIONERLIG', 'A', 'E', 'high', 'väl avpassad'),
    ('HEKTAR', 'D', 'A', 'high', 'ytmått, 10000 m²'),
    ('SEDERMERA', 'C', 'D', 'high', 'så småningom'),
    ('ATTRIBUT', 'B', 'E', 'high', 'kännetecken'),
    ('SNARSTUCKEN', 'A', 'C', 'high', 'lättstött'),
    ('MASKOPI', 'B', 'A', 'high', 'hemligt samförstånd'),
    ('ETERISK', 'C', 'B', 'high', 'flyktig, lätt'),
    ('HEREDITÄR', 'D', 'B', 'high', 'ärftlig'),
    ('HUSKUR', 'C', 'E', 'high', 'folklig behandlingsmetod'),
    ('TRÅNGSYNT', 'B', 'D', 'high', 'fördomsfull'),
    ('MÖDA', 'B', 'E', 'high', 'ansträngning'),
    ('RAFFINEMANG', 'C', 'E', 'high', 'förfining'),
    ('HYSA AGG', 'D', 'C', 'high', 'vara fientligt inställd'),
    ('KONTINUUM', 'C', 'D', 'high', 'obruten följd'),
    ('VIMMELKANTIG', 'B', 'A', 'high', 'yr'),
    ('KRILL', 'B', 'D', 'high', 'kräftdjur'),
    ('RESTRIKTIV', 'D', 'E', 'high', 'återhållsam'),
    ('SÄRDRAG', 'D', 'E', 'high', 'utmärkande egenskap'),
    ('EMPATI', 'C', 'D', 'high', 'inlevelseförmåga'),
    ('BORDLÄGGA', 'A', 'E', 'high', 'uppskjuta'),
    ('TAKTFULL', 'D', 'C', 'high', 'finkänslig'),
    ('BESTÅENDE', 'A', 'D', 'high', 'permanent'),
    ('HANDRÄCKNING', 'B', 'A', 'high', 'hjälp'),
    ('MOTHUGG', 'A', 'B', 'high', 'häftig kritik'),
    ('PORÖS', 'A', 'D', 'high', 'genomsläpplig'),
    ('SOLIDITET', 'C', 'D', 'high', 'finansiell stabilitet'),
    ('FÖRLORA MÅLFÖRET', 'C', 'B', 'high', 'bli stum'),
    ('OBEFOGAD', 'B', 'A', 'high', 'grundlös'),
    ('EMBALLAGE', 'A', 'B', 'high', 'förpackning'),
    ('TIDVIS', 'C', 'D', 'high', 'ibland'),
    ('FRAMFUSIG', 'D', 'E', 'high', 'påträngande'),
    ('EXTRAVAGANS', 'B', 'A', 'high', 'överdåd'),
    ('GE SIG TILL TÅLS', 'A', 'D', 'high', 'lugnt invänta'),
    ('BARYTON', 'B', 'C', 'high', 'röstläge'),
    ('MAXIM', 'B', 'E', 'high', 'levnadsregel'),
    ('IHÄRDIG', 'D', 'C', 'high', 'envis och uthållig'),
    ('HEREDITET', 'D', 'E', 'high', 'ärftlighet'),
    ('BEGRUNDA', 'B', 'D', 'high', 'fundera på'),
    ('KLÄDSAM', 'A', 'E', 'high', 'passande'),
    ('MED NÖD OCH NÄPPE', 'D', 'C', 'high', 'nästan inte'),
    ('UTFALL', 'B', 'D', 'high', 'resultat'),
    ('CEMENTERA', 'A', 'E', 'high', 'göra beständig'),
    ('TROLLBUNDEN', 'C', 'B', 'high', 'fascinerad'),
    ('VAG', 'C', 'A', 'high', 'obestämd'),
    ('MORALISERA', 'C', 'E', 'high', 'predika rätt och fel'),
    ('PÅ MÅFÅ', 'A', 'D', 'high', 'slumpmässigt'),
    ('MAUSOLEUM', 'C', 'A', 'high', 'gravbyggnad'),
    ('INSKRÄNKT', 'D', 'C', 'high', 'begränsad'),
    ('SKENRÄTTEGÅNG', 'B', 'D', 'high', 'avgjord på förhand'),
    ('VARA UNDER UPPSEGLING', 'C', 'A', 'high', 'närma sig'),
    ('SIGNUM', 'B', 'C', 'high', 'särmärke'),
    ('AVART', 'A', 'E', 'high', 'sämre variant'),
    ('ENAHANDA', 'B', 'D', 'high', 'enformig'),
    ('FEBRIL', 'B', 'E', 'high', 'hektisk'),
    ('METABOLISM', 'A', 'D', 'high', 'ämnesomsättning'),
    ('PURITAN', 'A', 'C', 'high', 'renlevnadsmänniska'),
    ('FÖRSUMMA', 'C', 'D', 'high', 'strunta i'),
    ('DUBIER', 'A', 'B', 'high', 'tvivel'),
    ('BLOTT', 'B', 'A', 'high', 'endast'),
    ('KOKETTERA', 'D', 'A', 'high', 'göra sig intressant'),
    ('KURAGE', 'C', 'D', 'high', 'tapperhet'),
    ('ABRUPT', 'A', 'C', 'high', 'plötsligt'),
    ('TORGFÖRA', 'C', 'B', 'high', 'öppet uttrycka'),
    ('PREFERENSER', 'D', 'E', 'high', 'något man föredrar'),
    ('NISCHAD', 'B', 'D', 'high', 'specialiserad'),
    ('DOMÄN', 'D', 'B', 'high', 'område'),
    ('SVULSTIG', 'B', 'C', 'high', 'alltför utsmyckad'),
    ('CELIAKI', 'C', 'A', 'high', 'glutenintolerans'),
    ('SÅTA VÄNNER', 'B', 'A', 'high', 'nära vänner'),
    ('SYMTOMATISK', 'B', 'D', 'high', 'kännetecknande'),
    ('DRÄNAGE', 'B', 'C', 'high', 'bortledning av vätska'),
    ('ÖGONBLICKLIGEN', 'C', 'B', 'high', 'utan dröjsmål'),
    ('ESKAPISM', 'B', 'E', 'high', 'verklighetsflykt'),
    ('ANVISA', 'C', 'A', 'high', 'tilldela'),
    ('JÄMKNING', 'C', 'E', 'high', 'anpassning'),
    ('MISSUNNSAM', 'B', 'E', 'high', 'ogenerös'),
    ('SKRÖNA', 'A', 'C', 'high', 'fantasifull berättelse'),
    ('REPRESENTERA', 'D', 'A', 'high', 'motsvara'),
    ('DEDUKTION', 'B', 'D', 'high', 'härledning'),
    ('SIGNALEMENT', 'D', 'E', 'high', 'beskrivning av person'),
    ('UPPSÅTLIG', 'A', 'E', 'high', 'avsiktlig'),
    ('TALG', 'B', 'C', 'high', 'fett'),
    ('KONTRASTERA', 'B', 'E', 'high', 'bilda motsats'),
    ('EKLIPS', 'C', 'D', 'high', 'förmörkelse'),
    ('SNART SAGT', 'D', 'A', 'high', 'så gott som'),
    ('AKTUALITET', 'B', 'D', 'high', 'nyhet'),
    ('INMUNDIGA', 'A', 'B', 'high', 'äta'),
    ('KRUM', 'B', 'A', 'high', 'böjd'),
    ('TIRADER', 'D', 'B', 'high', 'mångordiga yttranden'),
    ('KULMEN', 'C', 'E', 'high', 'höjdpunkt'),
    ('VERKNINGSFULLT', 'C', 'D', 'high', 'effektivt'),
    ('GE UPPHOV TILL', 'B', 'C', 'high', 'orsaka'),
    ('ENSEMBLE', 'D', 'E', 'high', 'grupp'),
    ('PROVOKATION', 'D', 'A', 'high', 'utmaning'),
    ('TAKTIL', 'A', 'B', 'high', 'känsel och beröring'),
    ('CHIMÄR', 'C', 'B', 'high', 'inbillning'),
    ('OBLAT', 'C', 'E', 'high', 'nattvardsbröd'),
    ('INFRIA', 'C', 'D', 'high', 'uppfylla (löfte)'),
    ('ALGEBRA', 'A', 'E', 'high', 'räkning med symboler'),
    ('RATIONELL', 'A', 'E', 'high', 'förnuftig'),
    ('TROJKA', 'C', 'D', 'high', 'tremannavälde'),
    ('SPORADISKT', 'D', 'C', 'high', 'vid enstaka tillfällen'),
    ('LAMELL', 'D', 'B', 'high', 'skiva'),
    ('ABONNERA', 'B', 'C', 'high', 'förhandsbeställa'),
    ('RUNDLIG', 'B', 'A', 'high', 'riklig'),
    ('KAKI', 'B', 'E', 'high', 'sandfärgat tyg'),
    ('ILLUSTRERA', 'C', 'D', 'high', 'belysa'),
    ('REMINISCENS', 'D', 'A', 'high', 'svag minnesbild'),
    ('SOM EN LÖPELD', 'D', 'E', 'high', 'snabbt'),
    ('DELIRIUM', 'D', 'C', 'high', 'förvirringstillstånd'),
    ('INNEVARANDE', 'C', 'B', 'high', 'pågående'),
    ('AVPOLLETTERA', 'D', 'B', 'high', 'skicka iväg'),
    ('FÖRORÄTTAD', 'C', 'D', 'high', 'sårad'),
    ('ANTOLOGI', 'B', 'A', 'high', 'textsamling'),
    ('NAIV', 'C', 'D', 'high', 'godtrogen'),
    ('HÖGAKTNING', 'C', 'E', 'high', 'vördnad'),
    ('KANDERA', 'B', 'C', 'high', 'överdra med socker'),
    ('FÖRBEHÅLL', 'C', 'A', 'high', 'villkor'),
    ('OAVVÄNT', 'C', 'B', 'high', 'oupphörligt'),
    ('KAROTEN', 'A', 'E', 'high', 'färgämne'),
    ('BRUKARE', 'A', 'B', 'high', 'vårdtagare/användare'),
    ('GENMÄLA', 'A', 'C', 'high', 'svara'),
    ('KANON', 'C', 'A', 'high', 'utvald samling'),
    ('PICCOLO', 'C', 'D', 'high', 'hotellpojke'),
    ('NYCKFULL', 'C', 'D', 'high', 'oberäknelig'),
    ('FÖREKOMST', 'B', 'E', 'high', 'existens'),
    ('IN NATURA', 'A', 'C', 'high', 'i annat värde än pengar'),
    ('MAKULATUR', 'A', 'D', 'high', 'kasserade trycksaker'),
    ('FÖRLIKNING', 'B', 'C', 'high', 'uppgörelse'),
    ('DERIVERA', 'C', 'B', 'high', 'härleda'),
    ('ALLUSION', 'C', 'E', 'high', 'anspelning'),
    ('FÖRSITTA', 'A', 'E', 'medium', 'primärbet: missa (sekundärbet: nöta finns)')
)
SELECT
  q.id,
  q.question_text AS word,
  q.correct_answer AS current_answer,
  pf.to_letter AS proposed_answer,
  pf.confidence,
  pf.why,
  q.options
FROM questions q
JOIN planned_fixes pf ON UPPER(q.question_text) = UPPER(pf.word)
WHERE q.category = 'ORD'
  AND q.correct_answer = pf.from_letter
ORDER BY pf.confidence DESC, q.question_text;