/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as TrainRouteImport } from './routes/train'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OrdRouteImport } from './routes/ord'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OmRouteImport } from './routes/om'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MatchmakingRouteImport } from './routes/matchmaking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as HogskoleprovetPoangraknareRouteImport } from './routes/hogskoleprovet-poangraknare'
import { Route as HogskoleprovetPoangRouteImport } from './routes/hogskoleprovet-poang'
import { Route as HogskoleprovetDatumRouteImport } from './routes/hogskoleprovet-datum'
import { Route as GamlaProvRouteImport } from './routes/gamla-prov'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuiderIndexRouteImport } from './routes/guider/index'
import { Route as ResultMatchIdRouteImport } from './routes/result.$matchId'
import { Route as OvaDelprovRouteImport } from './routes/ova.$delprov'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as JoinRoomCodeRouteImport } from './routes/join.$roomCode'
import { Route as GuiderXyzRouteImport } from './routes/guider/xyz'
import { Route as GuiderTidspressRouteImport } from './routes/guider/tidspress'
import { Route as GuiderOrdRouteImport } from './routes/guider/ord'
import { Route as GuiderNogRouteImport } from './routes/guider/nog'
import { Route as GuiderMekRouteImport } from './routes/guider/mek'
import { Route as GuiderLasRouteImport } from './routes/guider/las'
import { Route as GuiderKvaRouteImport } from './routes/guider/kva'
import { Route as GuiderElfRouteImport } from './routes/guider/elf'
import { Route as GuiderDtkRouteImport } from './routes/guider/dtk'
import { Route as GuiderBraResultatRouteImport } from './routes/guider/bra-resultat'
import { Route as GamlaProvTermRouteImport } from './routes/gamla-prov_.$term'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as GamlaProvTermPassRouteImport } from './routes/gamla-prov_.$term_.$pass'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdRoute = OrdRouteImport.update({
  id: '/ord',
  path: '/ord',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakingRoute = MatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const HogskoleprovetPoangraknareRoute =
  HogskoleprovetPoangraknareRouteImport.update({
    id: '/hogskoleprovet-poangraknare',
    path: '/hogskoleprovet-poangraknare',
    getParentRoute: () => rootRouteImport,
  } as any)
const HogskoleprovetPoangRoute = HogskoleprovetPoangRouteImport.update({
  id: '/hogskoleprovet-poang',
  path: '/hogskoleprovet-poang',
  getParentRoute: () => rootRouteImport,
} as any)
const HogskoleprovetDatumRoute = HogskoleprovetDatumRouteImport.update({
  id: '/hogskoleprovet-datum',
  path: '/hogskoleprovet-datum',
  getParentRoute: () => rootRouteImport,
} as any)
const GamlaProvRoute = GamlaProvRouteImport.update({
  id: '/gamla-prov',
  path: '/gamla-prov',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderIndexRoute = GuiderIndexRouteImport.update({
  id: '/guider/',
  path: '/guider/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultMatchIdRoute = ResultMatchIdRouteImport.update({
  id: '/result/$matchId',
  path: '/result/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const OvaDelprovRoute = OvaDelprovRouteImport.update({
  id: '/ova/$delprov',
  path: '/ova/$delprov',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoomCodeRoute = JoinRoomCodeRouteImport.update({
  id: '/join/$roomCode',
  path: '/join/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderXyzRoute = GuiderXyzRouteImport.update({
  id: '/guider/xyz',
  path: '/guider/xyz',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderTidspressRoute = GuiderTidspressRouteImport.update({
  id: '/guider/tidspress',
  path: '/guider/tidspress',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderOrdRoute = GuiderOrdRouteImport.update({
  id: '/guider/ord',
  path: '/guider/ord',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderNogRoute = GuiderNogRouteImport.update({
  id: '/guider/nog',
  path: '/guider/nog',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderMekRoute = GuiderMekRouteImport.update({
  id: '/guider/mek',
  path: '/guider/mek',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderLasRoute = GuiderLasRouteImport.update({
  id: '/guider/las',
  path: '/guider/las',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderKvaRoute = GuiderKvaRouteImport.update({
  id: '/guider/kva',
  path: '/guider/kva',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderElfRoute = GuiderElfRouteImport.update({
  id: '/guider/elf',
  path: '/guider/elf',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderDtkRoute = GuiderDtkRouteImport.update({
  id: '/guider/dtk',
  path: '/guider/dtk',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderBraResultatRoute = GuiderBraResultatRouteImport.update({
  id: '/guider/bra-resultat',
  path: '/guider/bra-resultat',
  getParentRoute: () => rootRouteImport,
} as any)
const GamlaProvTermRoute = GamlaProvTermRouteImport.update({
  id: '/gamla-prov_/$term',
  path: '/gamla-prov/$term',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamlaProvTermPassRoute = GamlaProvTermPassRouteImport.update({
  id: '/gamla-prov_/$term_/$pass',
  path: '/gamla-prov/$term/$pass',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/friends': typeof FriendsRoute
  '/gamla-prov': typeof GamlaProvRoute
  '/hogskoleprovet-datum': typeof HogskoleprovetDatumRoute
  '/hogskoleprovet-poang': typeof HogskoleprovetPoangRoute
  '/hogskoleprovet-poangraknare': typeof HogskoleprovetPoangraknareRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matchmaking': typeof MatchmakingRoute
  '/mcp': typeof McpRoute
  '/om': typeof OmRoute
  '/onboarding': typeof OnboardingRoute
  '/ord': typeof OrdRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/villkor': typeof VillkorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/gamla-prov/$term': typeof GamlaProvTermRoute
  '/guider/bra-resultat': typeof GuiderBraResultatRoute
  '/guider/dtk': typeof GuiderDtkRoute
  '/guider/elf': typeof GuiderElfRoute
  '/guider/kva': typeof GuiderKvaRoute
  '/guider/las': typeof GuiderLasRoute
  '/guider/mek': typeof GuiderMekRoute
  '/guider/nog': typeof GuiderNogRoute
  '/guider/ord': typeof GuiderOrdRoute
  '/guider/tidspress': typeof GuiderTidspressRoute
  '/guider/xyz': typeof GuiderXyzRoute
  '/join/$roomCode': typeof JoinRoomCodeRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/ova/$delprov': typeof OvaDelprovRoute
  '/result/$matchId': typeof ResultMatchIdRoute
  '/guider/': typeof GuiderIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/gamla-prov/$term/$pass': typeof GamlaProvTermPassRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/friends': typeof FriendsRoute
  '/gamla-prov': typeof GamlaProvRoute
  '/hogskoleprovet-datum': typeof HogskoleprovetDatumRoute
  '/hogskoleprovet-poang': typeof HogskoleprovetPoangRoute
  '/hogskoleprovet-poangraknare': typeof HogskoleprovetPoangraknareRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matchmaking': typeof MatchmakingRoute
  '/mcp': typeof McpRoute
  '/om': typeof OmRoute
  '/onboarding': typeof OnboardingRoute
  '/ord': typeof OrdRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/villkor': typeof VillkorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/gamla-prov/$term': typeof GamlaProvTermRoute
  '/guider/bra-resultat': typeof GuiderBraResultatRoute
  '/guider/dtk': typeof GuiderDtkRoute
  '/guider/elf': typeof GuiderElfRoute
  '/guider/kva': typeof GuiderKvaRoute
  '/guider/las': typeof GuiderLasRoute
  '/guider/mek': typeof GuiderMekRoute
  '/guider/nog': typeof GuiderNogRoute
  '/guider/ord': typeof GuiderOrdRoute
  '/guider/tidspress': typeof GuiderTidspressRoute
  '/guider/xyz': typeof GuiderXyzRoute
  '/join/$roomCode': typeof JoinRoomCodeRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/ova/$delprov': typeof OvaDelprovRoute
  '/result/$matchId': typeof ResultMatchIdRoute
  '/guider': typeof GuiderIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/gamla-prov/$term/$pass': typeof GamlaProvTermPassRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/friends': typeof FriendsRoute
  '/gamla-prov': typeof GamlaProvRoute
  '/hogskoleprovet-datum': typeof HogskoleprovetDatumRoute
  '/hogskoleprovet-poang': typeof HogskoleprovetPoangRoute
  '/hogskoleprovet-poangraknare': typeof HogskoleprovetPoangraknareRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matchmaking': typeof MatchmakingRoute
  '/mcp': typeof McpRoute
  '/om': typeof OmRoute
  '/onboarding': typeof OnboardingRoute
  '/ord': typeof OrdRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/villkor': typeof VillkorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/gamla-prov_/$term': typeof GamlaProvTermRoute
  '/guider/bra-resultat': typeof GuiderBraResultatRoute
  '/guider/dtk': typeof GuiderDtkRoute
  '/guider/elf': typeof GuiderElfRoute
  '/guider/kva': typeof GuiderKvaRoute
  '/guider/las': typeof GuiderLasRoute
  '/guider/mek': typeof GuiderMekRoute
  '/guider/nog': typeof GuiderNogRoute
  '/guider/ord': typeof GuiderOrdRoute
  '/guider/tidspress': typeof GuiderTidspressRoute
  '/guider/xyz': typeof GuiderXyzRoute
  '/join/$roomCode': typeof JoinRoomCodeRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/ova/$delprov': typeof OvaDelprovRoute
  '/result/$matchId': typeof ResultMatchIdRoute
  '/guider/': typeof GuiderIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/gamla-prov_/$term_/$pass': typeof GamlaProvTermPassRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/friends'
    | '/gamla-prov'
    | '/hogskoleprovet-datum'
    | '/hogskoleprovet-poang'
    | '/hogskoleprovet-poangraknare'
    | '/integritetspolicy'
    | '/kontakt'
    | '/leaderboard'
    | '/login'
    | '/matchmaking'
    | '/mcp'
    | '/om'
    | '/onboarding'
    | '/ord'
    | '/signup'
    | '/stats'
    | '/train'
    | '/villkor'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/gamla-prov/$term'
    | '/guider/bra-resultat'
    | '/guider/dtk'
    | '/guider/elf'
    | '/guider/kva'
    | '/guider/las'
    | '/guider/mek'
    | '/guider/nog'
    | '/guider/ord'
    | '/guider/tidspress'
    | '/guider/xyz'
    | '/join/$roomCode'
    | '/match/$matchId'
    | '/ova/$delprov'
    | '/result/$matchId'
    | '/guider/'
    | '/.mcp/invoke-tool/$tool'
    | '/gamla-prov/$term/$pass'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faq'
    | '/friends'
    | '/gamla-prov'
    | '/hogskoleprovet-datum'
    | '/hogskoleprovet-poang'
    | '/hogskoleprovet-poangraknare'
    | '/integritetspolicy'
    | '/kontakt'
    | '/leaderboard'
    | '/login'
    | '/matchmaking'
    | '/mcp'
    | '/om'
    | '/onboarding'
    | '/ord'
    | '/signup'
    | '/stats'
    | '/train'
    | '/villkor'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/gamla-prov/$term'
    | '/guider/bra-resultat'
    | '/guider/dtk'
    | '/guider/elf'
    | '/guider/kva'
    | '/guider/las'
    | '/guider/mek'
    | '/guider/nog'
    | '/guider/ord'
    | '/guider/tidspress'
    | '/guider/xyz'
    | '/join/$roomCode'
    | '/match/$matchId'
    | '/ova/$delprov'
    | '/result/$matchId'
    | '/guider'
    | '/.mcp/invoke-tool/$tool'
    | '/gamla-prov/$term/$pass'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/friends'
    | '/gamla-prov'
    | '/hogskoleprovet-datum'
    | '/hogskoleprovet-poang'
    | '/hogskoleprovet-poangraknare'
    | '/integritetspolicy'
    | '/kontakt'
    | '/leaderboard'
    | '/login'
    | '/matchmaking'
    | '/mcp'
    | '/om'
    | '/onboarding'
    | '/ord'
    | '/signup'
    | '/stats'
    | '/train'
    | '/villkor'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/gamla-prov_/$term'
    | '/guider/bra-resultat'
    | '/guider/dtk'
    | '/guider/elf'
    | '/guider/kva'
    | '/guider/las'
    | '/guider/mek'
    | '/guider/nog'
    | '/guider/ord'
    | '/guider/tidspress'
    | '/guider/xyz'
    | '/join/$roomCode'
    | '/match/$matchId'
    | '/ova/$delprov'
    | '/result/$matchId'
    | '/guider/'
    | '/.mcp/invoke-tool/$tool'
    | '/gamla-prov_/$term_/$pass'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  FriendsRoute: typeof FriendsRoute
  GamlaProvRoute: typeof GamlaProvRoute
  HogskoleprovetDatumRoute: typeof HogskoleprovetDatumRoute
  HogskoleprovetPoangRoute: typeof HogskoleprovetPoangRoute
  HogskoleprovetPoangraknareRoute: typeof HogskoleprovetPoangraknareRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  KontaktRoute: typeof KontaktRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MatchmakingRoute: typeof MatchmakingRoute
  McpRoute: typeof McpRoute
  OmRoute: typeof OmRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdRoute: typeof OrdRoute
  SignupRoute: typeof SignupRoute
  StatsRoute: typeof StatsRoute
  TrainRoute: typeof TrainRoute
  VillkorRoute: typeof VillkorRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  GamlaProvTermRoute: typeof GamlaProvTermRoute
  GuiderBraResultatRoute: typeof GuiderBraResultatRoute
  GuiderDtkRoute: typeof GuiderDtkRoute
  GuiderElfRoute: typeof GuiderElfRoute
  GuiderKvaRoute: typeof GuiderKvaRoute
  GuiderLasRoute: typeof GuiderLasRoute
  GuiderMekRoute: typeof GuiderMekRoute
  GuiderNogRoute: typeof GuiderNogRoute
  GuiderOrdRoute: typeof GuiderOrdRoute
  GuiderTidspressRoute: typeof GuiderTidspressRoute
  GuiderXyzRoute: typeof GuiderXyzRoute
  JoinRoomCodeRoute: typeof JoinRoomCodeRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  OvaDelprovRoute: typeof OvaDelprovRoute
  ResultMatchIdRoute: typeof ResultMatchIdRoute
  GuiderIndexRoute: typeof GuiderIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  GamlaProvTermPassRoute: typeof GamlaProvTermPassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ord': {
      id: '/ord'
      path: '/ord'
      fullPath: '/ord'
      preLoaderRoute: typeof OrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaking': {
      id: '/matchmaking'
      path: '/matchmaking'
      fullPath: '/matchmaking'
      preLoaderRoute: typeof MatchmakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hogskoleprovet-poangraknare': {
      id: '/hogskoleprovet-poangraknare'
      path: '/hogskoleprovet-poangraknare'
      fullPath: '/hogskoleprovet-poangraknare'
      preLoaderRoute: typeof HogskoleprovetPoangraknareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hogskoleprovet-poang': {
      id: '/hogskoleprovet-poang'
      path: '/hogskoleprovet-poang'
      fullPath: '/hogskoleprovet-poang'
      preLoaderRoute: typeof HogskoleprovetPoangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hogskoleprovet-datum': {
      id: '/hogskoleprovet-datum'
      path: '/hogskoleprovet-datum'
      fullPath: '/hogskoleprovet-datum'
      preLoaderRoute: typeof HogskoleprovetDatumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamla-prov': {
      id: '/gamla-prov'
      path: '/gamla-prov'
      fullPath: '/gamla-prov'
      preLoaderRoute: typeof GamlaProvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/': {
      id: '/guider/'
      path: '/guider'
      fullPath: '/guider/'
      preLoaderRoute: typeof GuiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$matchId': {
      id: '/result/$matchId'
      path: '/result/$matchId'
      fullPath: '/result/$matchId'
      preLoaderRoute: typeof ResultMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ova/$delprov': {
      id: '/ova/$delprov'
      path: '/ova/$delprov'
      fullPath: '/ova/$delprov'
      preLoaderRoute: typeof OvaDelprovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$roomCode': {
      id: '/join/$roomCode'
      path: '/join/$roomCode'
      fullPath: '/join/$roomCode'
      preLoaderRoute: typeof JoinRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/xyz': {
      id: '/guider/xyz'
      path: '/guider/xyz'
      fullPath: '/guider/xyz'
      preLoaderRoute: typeof GuiderXyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/tidspress': {
      id: '/guider/tidspress'
      path: '/guider/tidspress'
      fullPath: '/guider/tidspress'
      preLoaderRoute: typeof GuiderTidspressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/ord': {
      id: '/guider/ord'
      path: '/guider/ord'
      fullPath: '/guider/ord'
      preLoaderRoute: typeof GuiderOrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/nog': {
      id: '/guider/nog'
      path: '/guider/nog'
      fullPath: '/guider/nog'
      preLoaderRoute: typeof GuiderNogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/mek': {
      id: '/guider/mek'
      path: '/guider/mek'
      fullPath: '/guider/mek'
      preLoaderRoute: typeof GuiderMekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/las': {
      id: '/guider/las'
      path: '/guider/las'
      fullPath: '/guider/las'
      preLoaderRoute: typeof GuiderLasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/kva': {
      id: '/guider/kva'
      path: '/guider/kva'
      fullPath: '/guider/kva'
      preLoaderRoute: typeof GuiderKvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/elf': {
      id: '/guider/elf'
      path: '/guider/elf'
      fullPath: '/guider/elf'
      preLoaderRoute: typeof GuiderElfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/dtk': {
      id: '/guider/dtk'
      path: '/guider/dtk'
      fullPath: '/guider/dtk'
      preLoaderRoute: typeof GuiderDtkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/bra-resultat': {
      id: '/guider/bra-resultat'
      path: '/guider/bra-resultat'
      fullPath: '/guider/bra-resultat'
      preLoaderRoute: typeof GuiderBraResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamla-prov_/$term': {
      id: '/gamla-prov_/$term'
      path: '/gamla-prov/$term'
      fullPath: '/gamla-prov/$term'
      preLoaderRoute: typeof GamlaProvTermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamla-prov_/$term_/$pass': {
      id: '/gamla-prov_/$term_/$pass'
      path: '/gamla-prov/$term/$pass'
      fullPath: '/gamla-prov/$term/$pass'
      preLoaderRoute: typeof GamlaProvTermPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  FriendsRoute: FriendsRoute,
  GamlaProvRoute: GamlaProvRoute,
  HogskoleprovetDatumRoute: HogskoleprovetDatumRoute,
  HogskoleprovetPoangRoute: HogskoleprovetPoangRoute,
  HogskoleprovetPoangraknareRoute: HogskoleprovetPoangraknareRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  KontaktRoute: KontaktRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MatchmakingRoute: MatchmakingRoute,
  McpRoute: McpRoute,
  OmRoute: OmRoute,
  OnboardingRoute: OnboardingRoute,
  OrdRoute: OrdRoute,
  SignupRoute: SignupRoute,
  StatsRoute: StatsRoute,
  TrainRoute: TrainRoute,
  VillkorRoute: VillkorRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  GamlaProvTermRoute: GamlaProvTermRoute,
  GuiderBraResultatRoute: GuiderBraResultatRoute,
  GuiderDtkRoute: GuiderDtkRoute,
  GuiderElfRoute: GuiderElfRoute,
  GuiderKvaRoute: GuiderKvaRoute,
  GuiderLasRoute: GuiderLasRoute,
  GuiderMekRoute: GuiderMekRoute,
  GuiderNogRoute: GuiderNogRoute,
  GuiderOrdRoute: GuiderOrdRoute,
  GuiderTidspressRoute: GuiderTidspressRoute,
  GuiderXyzRoute: GuiderXyzRoute,
  JoinRoomCodeRoute: JoinRoomCodeRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  OvaDelprovRoute: OvaDelprovRoute,
  ResultMatchIdRoute: ResultMatchIdRoute,
  GuiderIndexRoute: GuiderIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  GamlaProvTermPassRoute: GamlaProvTermPassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
