/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainRouteImport } from './routes/train'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OrdRouteImport } from './routes/ord'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchmakingRouteImport } from './routes/matchmaking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultMatchIdRouteImport } from './routes/result.$matchId'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as JoinRoomCodeRouteImport } from './routes/join.$roomCode'

const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdRoute = OrdRouteImport.update({
  id: '/ord',
  path: '/ord',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakingRoute = MatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultMatchIdRoute = ResultMatchIdRouteImport.update({
  id: '/result/$matchId',
  path: '/result/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoomCodeRoute = JoinRoomCodeRouteImport.update({
  id: '/join/$roomCode',
  path: '/join/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matchmaking': typeof MatchmakingRoute
  '/onboarding': typeof OnboardingRoute
  '/ord': typeof OrdRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/join/$roomCode': typeof JoinRoomCodeRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/result/$matchId': typeof ResultMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matchmaking': typeof MatchmakingRoute
  '/onboarding': typeof OnboardingRoute
  '/ord': typeof OrdRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/join/$roomCode': typeof JoinRoomCodeRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/result/$matchId': typeof ResultMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matchmaking': typeof MatchmakingRoute
  '/onboarding': typeof OnboardingRoute
  '/ord': typeof OrdRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/join/$roomCode': typeof JoinRoomCodeRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/result/$matchId': typeof ResultMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/matchmaking'
    | '/onboarding'
    | '/ord'
    | '/signup'
    | '/stats'
    | '/train'
    | '/join/$roomCode'
    | '/match/$matchId'
    | '/result/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/matchmaking'
    | '/onboarding'
    | '/ord'
    | '/signup'
    | '/stats'
    | '/train'
    | '/join/$roomCode'
    | '/match/$matchId'
    | '/result/$matchId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/matchmaking'
    | '/onboarding'
    | '/ord'
    | '/signup'
    | '/stats'
    | '/train'
    | '/join/$roomCode'
    | '/match/$matchId'
    | '/result/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FriendsRoute: typeof FriendsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MatchmakingRoute: typeof MatchmakingRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdRoute: typeof OrdRoute
  SignupRoute: typeof SignupRoute
  StatsRoute: typeof StatsRoute
  TrainRoute: typeof TrainRoute
  JoinRoomCodeRoute: typeof JoinRoomCodeRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  ResultMatchIdRoute: typeof ResultMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ord': {
      id: '/ord'
      path: '/ord'
      fullPath: '/ord'
      preLoaderRoute: typeof OrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaking': {
      id: '/matchmaking'
      path: '/matchmaking'
      fullPath: '/matchmaking'
      preLoaderRoute: typeof MatchmakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$matchId': {
      id: '/result/$matchId'
      path: '/result/$matchId'
      fullPath: '/result/$matchId'
      preLoaderRoute: typeof ResultMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$roomCode': {
      id: '/join/$roomCode'
      path: '/join/$roomCode'
      fullPath: '/join/$roomCode'
      preLoaderRoute: typeof JoinRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FriendsRoute: FriendsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MatchmakingRoute: MatchmakingRoute,
  OnboardingRoute: OnboardingRoute,
  OrdRoute: OrdRoute,
  SignupRoute: SignupRoute,
  StatsRoute: StatsRoute,
  TrainRoute: TrainRoute,
  JoinRoomCodeRoute: JoinRoomCodeRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  ResultMatchIdRoute: ResultMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
