-- Migration: fixa felaktiga correct_answer-värden för ORD-frågor
-- Genererad efter manuell granskning av alla 459 HP-frågor (Claude 2026-05-14).
-- ~22% felfrekvens hittades pga scraper-fel där facit parsades från fel kolumn.
-- Idempotent: varje UPDATE har 'AND correct_answer = X' så redan rättade rader rörs ej.
-- 132 high-confidence fixar + 1 medium-confidence fixar.

-- ============ HIGH-CONFIDENCE ============
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('OFFERT') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('PROPORTIONERLIG') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('HEKTAR') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('SEDERMERA') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('ATTRIBUT') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('SNARSTUCKEN') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('MASKOPI') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('ETERISK') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('HEREDITÄR') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('HUSKUR') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('TRÅNGSYNT') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('MÖDA') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('RAFFINEMANG') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('HYSA AGG') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('KONTINUUM') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('VIMMELKANTIG') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('KRILL') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('RESTRIKTIV') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('SÄRDRAG') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('EMPATI') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('BORDLÄGGA') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('TAKTFULL') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('BESTÅENDE') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('HANDRÄCKNING') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('MOTHUGG') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('PORÖS') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('SOLIDITET') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('FÖRLORA MÅLFÖRET') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('OBEFOGAD') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('EMBALLAGE') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('TIDVIS') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('FRAMFUSIG') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('EXTRAVAGANS') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('GE SIG TILL TÅLS') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('BARYTON') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('MAXIM') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('IHÄRDIG') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('HEREDITET') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('BEGRUNDA') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('KLÄDSAM') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('MED NÖD OCH NÄPPE') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('UTFALL') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('CEMENTERA') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('TROLLBUNDEN') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('VAG') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('MORALISERA') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('PÅ MÅFÅ') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('MAUSOLEUM') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('INSKRÄNKT') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('SKENRÄTTEGÅNG') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('VARA UNDER UPPSEGLING') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('SIGNUM') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('AVART') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('ENAHANDA') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('FEBRIL') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('METABOLISM') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('PURITAN') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('FÖRSUMMA') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('DUBIER') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('BLOTT') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('KOKETTERA') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('KURAGE') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('ABRUPT') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('TORGFÖRA') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('PREFERENSER') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('NISCHAD') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('DOMÄN') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('SVULSTIG') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('CELIAKI') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('SÅTA VÄNNER') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('SYMTOMATISK') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('DRÄNAGE') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('ÖGONBLICKLIGEN') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('ESKAPISM') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('ANVISA') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('JÄMKNING') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('MISSUNNSAM') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('SKRÖNA') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('REPRESENTERA') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('DEDUKTION') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('SIGNALEMENT') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('UPPSÅTLIG') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('TALG') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('KONTRASTERA') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('EKLIPS') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('SNART SAGT') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('AKTUALITET') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('INMUNDIGA') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('KRUM') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('TIRADER') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('KULMEN') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('VERKNINGSFULLT') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('GE UPPHOV TILL') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('ENSEMBLE') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('PROVOKATION') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('TAKTIL') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('CHIMÄR') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('OBLAT') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('INFRIA') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('ALGEBRA') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('RATIONELL') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('TROJKA') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('SPORADISKT') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('LAMELL') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('ABONNERA') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('RUNDLIG') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('KAKI') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('ILLUSTRERA') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('REMINISCENS') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('SOM EN LÖPELD') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('DELIRIUM') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('INNEVARANDE') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('AVPOLLETTERA') AND correct_answer = 'D';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('FÖRORÄTTAD') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('ANTOLOGI') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('NAIV') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('HÖGAKTNING') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('KANDERA') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('FÖRBEHÅLL') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('OAVVÄNT') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('KAROTEN') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('BRUKARE') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('GENMÄLA') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'A' WHERE category = 'ORD' AND upper(question_text) = upper('KANON') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('PICCOLO') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('NYCKFULL') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('FÖREKOMST') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('IN NATURA') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'D' WHERE category = 'ORD' AND upper(question_text) = upper('MAKULATUR') AND correct_answer = 'A';
UPDATE public.questions SET correct_answer = 'C' WHERE category = 'ORD' AND upper(question_text) = upper('FÖRLIKNING') AND correct_answer = 'B';
UPDATE public.questions SET correct_answer = 'B' WHERE category = 'ORD' AND upper(question_text) = upper('DERIVERA') AND correct_answer = 'C';
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('ALLUSION') AND correct_answer = 'C';

-- ============ MEDIUM-CONFIDENCE ============
UPDATE public.questions SET correct_answer = 'E' WHERE category = 'ORD' AND upper(question_text) = upper('FÖRSITTA') AND correct_answer = 'A';
